---
title: "Adverse Childhood Events and Impulsive-Like Behavior"
format: revealjs
---



```{r, ALL PACKAGES AND DATA, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(readr)
library(here)
library(haven)
library(emmeans)
library(lmerTest)
library(lme4)
library(plotly)
library(maps)
library(mapproj)
library(usmap)
library(knitr)
library(broom)
library(gridExtra)

twenty022 <- read_xpt(here::here("LLCP2022.XPT ")) ## space after T 
twenty021 <- read_xpt(here::here("LLCP2021.XPT"))
twenty020 <- read_xpt(here::here("LLCP2020.XPT"))
twenty019 <- read_xpt(here::here("LLCP2019.XPT"))

## 2022: 
twenty022 = twenty022 |> select(
                    IYEAR, '_STATE', SEXVAR, MARITAL, VETERAN3, INCOME3, "_BMI5", 
                    EDUCA, RENTHOM1, EMPLOY1, CHILDREN, CAREGIV1, CRGVREL4, CRGVLNG1, CRGVPRB3, SDHEMPLY, FOODSTMP, SDHFOOD1, SDHBILLS, SDHUTILS, SOMALE, TRNSGNDR, RRCLASS3, "_METSTAT", "_URBSTAT", "_IMPRACE", "_AGE_G",
                    GENHLTH, PHYSHLTH, MENTHLTH, POORHLTH, EXERANY2, SLEPTIM1, LASTDEN4, CVDINFR4, CVDCRHD4, CVDSTRK3, ASTHMA3, CHCSCNC1, CHCOCNC1, CHCCOPD3, ADDEPEV3, CHCKDNY2, HAVARTH4, DIABETE4, DEAF, BLIND, DIFFWALK, DIFFDRES, DIFFALON, PREDIAB2,
                      DIABTYPE, CNCRTYP2,  LSATISFY, EMTSUPRT, SDHISOLT, SDHSTRE1, 
                    SMOKE100, SMOKDAY2, USENOW3, ECIGNOW2, LCSFIRST, LCSLAST, LCSNUMCG, LCSSCNCR, ALCDAY4, AVEDRNK3, DRNK3GE5, MAXDRNKS, COPDSMOK, MARIJAN1, MARJSMOK, LASTSMK2, 
                    PRIMINSR, MEDCOST1, 
                    ACEDEPRS, ACEDRINK, ACEDRUGS, ACEPRISN, 
                    ACEDIVRC, ACEPUNCH, ACEHURT1, ACESWEAR,
                    ACETOUCH, ACETTHEM, ACEHVSEX, ACEADSAF, 
                    ACEADNED) |> 
  filter(!is.na(ACEDEPRS) | !is.na(ACEDRINK) | !is.na(ACEDRUGS) | !is.na(ACEPRISN) | 
           !is.na(ACEDIVRC) | !is.na(ACEPUNCH) | !is.na(ACEHURT1) | !is.na(ACESWEAR) | 
           !is.na(ACETOUCH) | !is.na(ACETTHEM) | !is.na(ACEHVSEX) | !is.na(ACEADSAF) |
           !is.na(ACEADNED)) |>
  rename("state" = "_STATE",
         "age" = "_AGE_G",
         "race" = "_IMPRACE",
         "sex" = SEXVAR,
        "MentalIllness" = ACEDEPRS,
         "Alcoholic" = ACEDRINK,
         "SubstanceAddiction" = ACEDRUGS,
         "Incarcerated" = ACEPRISN,
         "SeparationDivorce" = ACEDIVRC,
         "DomesticViolence" = ACEPUNCH,
         "PhysicalAbuse" = ACEHURT1,
         "EmotionalAbuse" = ACESWEAR,
         "SexualAbuse1" = ACETOUCH,
         "SexualAbuse2" = ACETTHEM,
         "SexualAbuse3" = ACEHVSEX,
         "Neglect1" = ACEADSAF,
         "Neglect2" = ACEADNED) |>
mutate(MentalIllness = case_when(
  MentalIllness == 1 ~ 1,
  MentalIllness == 2 ~ 0,
  MentalIllness == 7 ~ NA,
  MentalIllness == 9 ~ NA)) |>
  mutate(Alcoholic = case_when(
    Alcoholic == 1 ~ 1,
    Alcoholic == 2 ~ 0,
    Alcoholic == 7 ~ NA,
    Alcoholic == 9 ~ NA)) |> 
  mutate(SubstanceAddiction = case_when(
    SubstanceAddiction == 1 ~ 1,
    SubstanceAddiction == 2 ~ 0,
    SubstanceAddiction == 7 ~ NA,
    SubstanceAddiction == 9 ~ NA)) |>
  mutate(Incarcerated = case_when(
    Incarcerated == 1 ~ 1,
    Incarcerated == 2 ~ 0,
    Incarcerated == 7 ~ NA,
    Incarcerated == 9 ~ NA)) |> 
  mutate(SeparationDivorce = case_when(
    SeparationDivorce == 1 ~ 1,
    SeparationDivorce == 2 ~ 0,
    SeparationDivorce == 7 ~ NA,
    SeparationDivorce == 8 ~ NA,
    SeparationDivorce == 9 ~ NA)) |>
  mutate(DomesticViolence = case_when(
    DomesticViolence == 1 ~ 0,
    DomesticViolence == 2 ~ 1, 
    DomesticViolence == 3 ~ 1,
    DomesticViolence == 7 ~ NA,
    DomesticViolence == 9 ~ NA)) |>
  mutate(PhysicalAbuse = case_when(
    PhysicalAbuse == 1 ~ 0,
    PhysicalAbuse == 2 ~ 1,
    PhysicalAbuse == 3 ~ 1,
    PhysicalAbuse == 7 ~ NA,
    PhysicalAbuse == 9 ~ NA)) |>
  mutate(EmotionalAbuse = case_when(
    EmotionalAbuse == 1 ~ 0,
    EmotionalAbuse == 2 ~ 1, 
    EmotionalAbuse == 3 ~ 1,
    EmotionalAbuse == 7 ~ NA,
    EmotionalAbuse == 9 ~ NA)) |>
  mutate(SexualAbuse1 = case_when(
    SexualAbuse1 == 1 ~ 0,
    SexualAbuse1 == 2 ~ 1,
    SexualAbuse1 == 3 ~ 1,
    SexualAbuse1 == 7 ~ NA,
    SexualAbuse1 == 9 ~ NA)) |>
  mutate(SexualAbuse2 = case_when(
    SexualAbuse2 == 1 ~ 0,
    SexualAbuse2 == 2 ~ 1,
    SexualAbuse2 == 3 ~ 1,
    SexualAbuse2 == 7 ~ NA,
    SexualAbuse2 == 9 ~ NA)) |> 
  mutate(SexualAbuse3 = case_when(
    SexualAbuse3 == 1 ~ 0,
    SexualAbuse3 == 2 ~ 1,
    SexualAbuse3 == 3 ~ 1,
    SexualAbuse3 == 7 ~ NA,
    SexualAbuse3 == 9 ~ NA)) |>
  mutate(Neglect1 = case_when(
    Neglect1 == NA ~ NA,
    Neglect1 == 1 ~ 0,
    Neglect1 == 2 ~ 1,
    Neglect1 == 3 ~ 1,
    Neglect1 == 4 ~ 1,
    Neglect1 == 5 ~ 1,
    Neglect1 == 7 ~ NA,
    Neglect1 == 9 ~ NA)) |>
  mutate(Neglect2 = case_when(
    Neglect2 == 1 ~ 0,
    Neglect2 == 2 ~ 1,
    Neglect2 == 3 ~ 1,
    Neglect2 == 4 ~ 1,
    Neglect2 == 5 ~ 1,
    Neglect2 == NA ~ NA,
    Neglect2 == 7 ~ NA,
    Neglect2 == 9 ~ NA)) |>
  mutate(number = 1)

## 2021: 
twenty021 = twenty021 |> select(
                    IYEAR, '_STATE', SEXVAR, MARITAL, VETERAN3, INCOME3, "_BMI5",
                    EDUCA, RENTHOM1, EMPLOY1, CHILDREN, CAREGIV1, CRGVREL4, CRGVLNG1, CRGVPRB3, SOMALE, TRNSGNDR, "_METSTAT", "_URBSTAT", "_IMPRACE", "_AGE_G",
                    GENHLTH, PHYSHLTH, MENTHLTH, POORHLTH, EXERANY2, CVDINFR4, CVDCRHD4, CVDSTRK3, ASTHMA3, ADDEPEV3, CHCKDNY2, DIABETE4, DEAF, BLIND, DIFFWALK, DIFFDRES, DIFFALON,
                    SMOKE100, SMOKDAY2, USENOW3, LCSFIRST, LCSLAST, LCSNUMCG, ECIGNOW1, AVEDRNK3, ALCDAY5, DRNK3GE5, MAXDRNKS, MARIJAN1, LASTSMK2, 
                    PRIMINSR, MEDCOST1, 
                    ACEDEPRS, ACEDRINK, ACEDRUGS, ACEPRISN, 
                    ACEDIVRC, ACEPUNCH, ACEHURT1, ACESWEAR,
                    ACETOUCH, ACETTHEM, ACEHVSEX, ACEADSAF, 
                    ACEADNED) |> 
  filter(!is.na(ACEDEPRS) | !is.na(ACEDRINK) | !is.na(ACEDRUGS) | !is.na(ACEPRISN) | 
           !is.na(ACEDIVRC) | !is.na(ACEPUNCH) | !is.na(ACEHURT1) | !is.na(ACESWEAR) | 
           !is.na(ACETOUCH) | !is.na(ACETTHEM) | !is.na(ACEHVSEX) | !is.na(ACEADSAF) |
           !is.na(ACEADNED)) |>
  rename("state" = "_STATE",
         "age" = "_AGE_G",
         "race" = "_IMPRACE",
         "sex" = SEXVAR,
        "MentalIllness" = ACEDEPRS,
         "Alcoholic" = ACEDRINK,
         "SubstanceAddiction" = ACEDRUGS,
         "Incarcerated" = ACEPRISN,
         "SeparationDivorce" = ACEDIVRC,
         "DomesticViolence" = ACEPUNCH,
         "PhysicalAbuse" = ACEHURT1,
         "EmotionalAbuse" = ACESWEAR,
         "SexualAbuse1" = ACETOUCH,
         "SexualAbuse2" = ACETTHEM,
         "SexualAbuse3" = ACEHVSEX,
         "Neglect1" = ACEADSAF,
         "Neglect2" = ACEADNED) |> 
  mutate(MentalIllness = case_when(
  MentalIllness == 1 ~ 1,
  MentalIllness == 2 ~ 0,
  MentalIllness == 7 ~ NA,
  MentalIllness == 9 ~ NA)) |>
  mutate(Alcoholic = case_when(
    Alcoholic == 1 ~ 1,
    Alcoholic == 2 ~ 0,
    Alcoholic == 7 ~ NA,
    Alcoholic == 9 ~ NA)) |> 
  mutate(SubstanceAddiction = case_when(
    SubstanceAddiction == 1 ~ 1,
    SubstanceAddiction == 2 ~ 0,
    SubstanceAddiction == 7 ~ NA,
    SubstanceAddiction == 9 ~ NA)) |>
  mutate(Incarcerated = case_when(
    Incarcerated == 1 ~ 1,
    Incarcerated == 2 ~ 0,
    Incarcerated == 7 ~ NA,
    Incarcerated == 9 ~ NA)) |> 
  mutate(SeparationDivorce = case_when(
    SeparationDivorce == 1 ~ 1,
    SeparationDivorce == 2 ~ 0,
    SeparationDivorce == 7 ~ NA,
    SeparationDivorce == 8 ~ NA,
    SeparationDivorce == 9 ~ NA)) |>
  mutate(DomesticViolence = case_when(
    DomesticViolence == 1 ~ 0,
    DomesticViolence == 2 ~ 1, 
    DomesticViolence == 3 ~ 1,
    DomesticViolence == 7 ~ NA,
    DomesticViolence == 9 ~ NA)) |>
  mutate(PhysicalAbuse = case_when(
    PhysicalAbuse == 1 ~ 0,
    PhysicalAbuse == 2 ~ 1,
    PhysicalAbuse == 3 ~ 1,
    PhysicalAbuse == 7 ~ NA,
    PhysicalAbuse == 9 ~ NA)) |>
  mutate(EmotionalAbuse = case_when(
    EmotionalAbuse == 1 ~ 0,
    EmotionalAbuse == 2 ~ 1, 
    EmotionalAbuse == 3 ~ 1,
    EmotionalAbuse == 7 ~ NA,
    EmotionalAbuse == 9 ~ NA)) |>
  mutate(SexualAbuse1 = case_when(
    SexualAbuse1 == 1 ~ 0,
    SexualAbuse1 == 2 ~ 1,
    SexualAbuse1 == 3 ~ 1,
    SexualAbuse1 == 7 ~ NA,
    SexualAbuse1 == 9 ~ NA)) |>
  mutate(SexualAbuse2 = case_when(
    SexualAbuse2 == 1 ~ 0,
    SexualAbuse2 == 2 ~ 1,
    SexualAbuse2 == 3 ~ 1,
    SexualAbuse2 == 7 ~ NA,
    SexualAbuse2 == 9 ~ NA)) |> 
  mutate(SexualAbuse3 = case_when(
    SexualAbuse3 == 1 ~ 0,
    SexualAbuse3 == 2 ~ 1,
    SexualAbuse3 == 3 ~ 1,
    SexualAbuse3 == 7 ~ NA,
    SexualAbuse3 == 9 ~ NA)) |>
  mutate(Neglect1 = case_when(
    Neglect1 == NA ~ NA,
    Neglect1 == 1 ~ 0,
    Neglect1 == 2 ~ 1,
    Neglect1 == 3 ~ 1,
    Neglect1 == 4 ~ 1,
    Neglect1 == 5 ~ 1,
    Neglect1 == 7 ~ NA,
    Neglect1 == 9 ~ NA)) |>
  mutate(Neglect2 = case_when(
    Neglect2 == 1 ~ 0,
    Neglect2 == 2 ~ 1,
    Neglect2 == 3 ~ 1,
    Neglect2 == 4 ~ 1,
    Neglect2 == 5 ~ 1,
    Neglect2 == NA ~ NA,
    Neglect2 == 7 ~ NA,
    Neglect2 == 9 ~ NA)) |>
  mutate(number = 2)

## 2020: 

twenty020 = twenty020 |> select(
                    IYEAR, '_STATE', SEXVAR, MARITAL, VETERAN3, INCOME2, WEIGHT2, HEIGHT3, 
                    EDUCA, RENTHOM1, EMPLOY1, CHILDREN, CAREGIV1, CRGVREL4, CRGVLNG1, CRGVPRB3, SOMALE, TRNSGNDR, "_METSTAT", "_URBSTAT", "_IMPRACE", "_AGE_G",
                    GENHLTH, PHYSHLTH, MENTHLTH, POORHLTH, EXERANY2, CVDINFR4, CVDCRHD4, CVDSTRK3, ASTHMA3, ADDEPEV3, CHCKDNY2, DIABETE4, DEAF, BLIND, DIFFWALK, DIFFDRES, DIFFALON,
                    SMOKE100, SMOKDAY2, USENOW3, LCSFIRST, LCSLAST, LCSNUMCG, ECIGNOW, AVEDRNK3, ALCDAY5, DRNK3GE5, MAXDRNKS, MARIJAN1, LASTSMK2, 
                    HLTHCVR1,
                    ACEDEPRS, ACEDRINK, ACEDRUGS, ACEPRISN, 
                    ACEDIVRC, ACEPUNCH, ACEHURT1, ACESWEAR,
                    ACETOUCH, ACETTHEM, ACEHVSEX) |> 
  filter(!is.na(ACEDEPRS) | !is.na(ACEDRINK) | !is.na(ACEDRUGS) | !is.na(ACEPRISN) | 
           !is.na(ACEDIVRC) | !is.na(ACEPUNCH) | !is.na(ACEHURT1) | !is.na(ACESWEAR) | 
           !is.na(ACETOUCH) | !is.na(ACETTHEM) | !is.na(ACEHVSEX)) |>
  rename("state" = "_STATE",
         "age" = "_AGE_G",
         "race" = "_IMPRACE",
         "sex" = SEXVAR,
        "MentalIllness" = ACEDEPRS,
         "Alcoholic" = ACEDRINK,
         "SubstanceAddiction" = ACEDRUGS,
         "Incarcerated" = ACEPRISN,
         "SeparationDivorce" = ACEDIVRC,
         "DomesticViolence" = ACEPUNCH,
         "PhysicalAbuse" = ACEHURT1,
         "EmotionalAbuse" = ACESWEAR,
         "SexualAbuse1" = ACETOUCH,
         "SexualAbuse2" = ACETTHEM,
         "SexualAbuse3" = ACEHVSEX) |>
  mutate(MentalIllness = case_when(
  MentalIllness == 1 ~ 1,
  MentalIllness == 2 ~ 0,
  MentalIllness == 7 ~ NA,
  MentalIllness == 9 ~ NA)) |>
  mutate(Alcoholic = case_when(
    Alcoholic == 1 ~ 1,
    Alcoholic == 2 ~ 0,
    Alcoholic == 7 ~ NA,
    Alcoholic == 9 ~ NA)) |> 
  mutate(SubstanceAddiction = case_when(
    SubstanceAddiction == 1 ~ 1,
    SubstanceAddiction == 2 ~ 0,
    SubstanceAddiction == 7 ~ NA,
    SubstanceAddiction == 9 ~ NA)) |>
  mutate(Incarcerated = case_when(
    Incarcerated == 1 ~ 1,
    Incarcerated == 2 ~ 0,
    Incarcerated == 7 ~ NA,
    Incarcerated == 9 ~ NA)) |> 
  mutate(SeparationDivorce = case_when(
    SeparationDivorce == 1 ~ 1,
    SeparationDivorce == 2 ~ 0,
    SeparationDivorce == 7 ~ NA,
    SeparationDivorce == 8 ~ NA,
    SeparationDivorce == 9 ~ NA)) |>
  mutate(DomesticViolence = case_when(
    DomesticViolence == 1 ~ 0,
    DomesticViolence == 2 ~ 1, 
    DomesticViolence == 3 ~ 1,
    DomesticViolence == 7 ~ NA,
    DomesticViolence == 9 ~ NA)) |>
  mutate(PhysicalAbuse = case_when(
    PhysicalAbuse == 1 ~ 0,
    PhysicalAbuse == 2 ~ 1,
    PhysicalAbuse == 3 ~ 1,
    PhysicalAbuse == 7 ~ NA,
    PhysicalAbuse == 9 ~ NA)) |>
  mutate(EmotionalAbuse = case_when(
    EmotionalAbuse == 1 ~ 0,
    EmotionalAbuse == 2 ~ 1, 
    EmotionalAbuse == 3 ~ 1,
    EmotionalAbuse == 7 ~ NA,
    EmotionalAbuse == 9 ~ NA)) |>
  mutate(SexualAbuse1 = case_when(
    SexualAbuse1 == 1 ~ 0,
    SexualAbuse1 == 2 ~ 1,
    SexualAbuse1 == 3 ~ 1,
    SexualAbuse1 == 7 ~ NA,
    SexualAbuse1 == 9 ~ NA)) |>
  mutate(SexualAbuse2 = case_when(
    SexualAbuse2 == 1 ~ 0,
    SexualAbuse2 == 2 ~ 1,
    SexualAbuse2 == 3 ~ 1,
    SexualAbuse2 == 7 ~ NA,
    SexualAbuse2 == 9 ~ NA)) |> 
  mutate(SexualAbuse3 = case_when(
    SexualAbuse3 == 1 ~ 0,
    SexualAbuse3 == 2 ~ 1,
    SexualAbuse3 == 3 ~ 1,
    SexualAbuse3 == 7 ~ NA,
    SexualAbuse3 == 9 ~ NA)) |>
  mutate(number = 3)

# 2019: 

twenty019 = twenty019 |> select(
                    IYEAR, '_STATE', SEXVAR, MARITAL, VETERAN3, INCOME2, WEIGHT2, HEIGHT3, 
                    EDUCA, RENTHOM1, EMPLOY1, CHILDREN, CAREGIV1, CRGVLNG1, CRGVPRB3, SOMALE, TRNSGNDR, "_METSTAT", "_URBSTAT", "_IMPRACE", "_AGE_G",
                    GENHLTH, PHYSHLTH, MENTHLTH, POORHLTH, EXERANY2, CVDINFR4, CVDCRHD4, CVDSTRK3, ASTHMA3, ADDEPEV3, CHCKDNY2, DIABETE4, DEAF, BLIND, DIFFWALK, DIFFDRES, DIFFALON,
                    SMOKE100, SMOKDAY2, USENOW3, LCSFIRST, LCSLAST, LCSNUMCG, ALCDAY5, AVEDRNK3, DRNK3GE5, MAXDRNKS, MARIJAN1, LASTSMK2, 
                    HLTHCVR1,
                    ACEDEPRS, ACEDRINK, ACEDRUGS, ACEPRISN, 
                    ACEDIVRC, ACEPUNCH, ACEHURT1, ACESWEAR,
                    ACETOUCH, ACETTHEM, ACEHVSEX) |> 
  filter(!is.na(ACEDEPRS) | !is.na(ACEDRINK) | !is.na(ACEDRUGS) | !is.na(ACEPRISN) | 
           !is.na(ACEDIVRC) | !is.na(ACEPUNCH) | !is.na(ACEHURT1) | !is.na(ACESWEAR) | 
           !is.na(ACETOUCH) | !is.na(ACETTHEM) | !is.na(ACEHVSEX)) |>
  rename("state" = "_STATE",
         "age" = "_AGE_G",
         "race" = "_IMPRACE",
         "sex" = SEXVAR,
        "MentalIllness" = ACEDEPRS,
         "Alcoholic" = ACEDRINK,
         "SubstanceAddiction" = ACEDRUGS,
         "Incarcerated" = ACEPRISN,
         "SeparationDivorce" = ACEDIVRC,
         "DomesticViolence" = ACEPUNCH,
         "PhysicalAbuse" = ACEHURT1,
         "EmotionalAbuse" = ACESWEAR,
         "SexualAbuse1" = ACETOUCH,
         "SexualAbuse2" = ACETTHEM,
         "SexualAbuse3" = ACEHVSEX) |>
  mutate(MentalIllness = case_when(
  MentalIllness == 1 ~ 1,
  MentalIllness == 2 ~ 0,
  MentalIllness == 7 ~ NA,
  MentalIllness == 9 ~ NA)) |>
  mutate(Alcoholic = case_when(
    Alcoholic == 1 ~ 1,
    Alcoholic == 2 ~ 0,
    Alcoholic == 7 ~ NA,
    Alcoholic == 9 ~ NA)) |> 
  mutate(SubstanceAddiction = case_when(
    SubstanceAddiction == 1 ~ 1,
    SubstanceAddiction == 2 ~ 0,
    SubstanceAddiction == 7 ~ NA,
    SubstanceAddiction == 9 ~ NA)) |>
  mutate(Incarcerated = case_when(
    Incarcerated == 1 ~ 1,
    Incarcerated == 2 ~ 0,
    Incarcerated == 7 ~ NA,
    Incarcerated == 9 ~ NA)) |> 
  mutate(SeparationDivorce = case_when(
    SeparationDivorce == 1 ~ 1,
    SeparationDivorce == 2 ~ 0,
    SeparationDivorce == 7 ~ NA,
    SeparationDivorce == 8 ~ NA,
    SeparationDivorce == 9 ~ NA)) |>
  mutate(DomesticViolence = case_when(
    DomesticViolence == 1 ~ 0,
    DomesticViolence == 2 ~ 1, 
    DomesticViolence == 3 ~ 1,
    DomesticViolence == 7 ~ NA,
    DomesticViolence == 9 ~ NA)) |>
  mutate(PhysicalAbuse = case_when(
    PhysicalAbuse == 1 ~ 0,
    PhysicalAbuse == 2 ~ 1,
    PhysicalAbuse == 3 ~ 1,
    PhysicalAbuse == 7 ~ NA,
    PhysicalAbuse == 9 ~ NA)) |>
  mutate(EmotionalAbuse = case_when(
    EmotionalAbuse == 1 ~ 0,
    EmotionalAbuse == 2 ~ 1, 
    EmotionalAbuse == 3 ~ 1,
    EmotionalAbuse == 7 ~ NA,
    EmotionalAbuse == 9 ~ NA)) |>
  mutate(SexualAbuse1 = case_when(
    SexualAbuse1 == 1 ~ 0,
    SexualAbuse1 == 2 ~ 1,
    SexualAbuse1 == 3 ~ 1,
    SexualAbuse1 == 7 ~ NA,
    SexualAbuse1 == 9 ~ NA)) |>
  mutate(SexualAbuse2 = case_when(
    SexualAbuse2 == 1 ~ 0,
    SexualAbuse2 == 2 ~ 1,
    SexualAbuse2 == 3 ~ 1,
    SexualAbuse2 == 7 ~ NA,
    SexualAbuse2 == 9 ~ NA)) |> 
  mutate(SexualAbuse3 = case_when(
    SexualAbuse3 == 1 ~ 0,
    SexualAbuse3 == 2 ~ 1,
    SexualAbuse3 == 3 ~ 1,
    SexualAbuse3 == 7 ~ NA,
    SexualAbuse3 == 9 ~ NA)) |>
  mutate(number = 4)

## Dataset that inclueds everything: 
everything = full_join(twenty019, full_join(twenty020, full_join(twenty021, twenty022)))

```


```{r echo=FALSE}
perweek = everything |> select(MentalIllness, Alcoholic, Incarcerated, SeparationDivorce, DomesticViolence, PhysicalAbuse, EmotionalAbuse, SexualAbuse1, SexualAbuse2, SexualAbuse3, Neglect1, Neglect2, SubstanceAddiction, ALCDAY4, ALCDAY5, sex, age, race, number) |>
  mutate(perweek = case_when(
    ALCDAY5 == 101 ~ 1,
    ALCDAY5 == 102 ~ 2, 
    ALCDAY5 == 103 ~ 3,
    ALCDAY5 == 104 ~ 4, 
    ALCDAY5 == 105 ~ 5,
    ALCDAY5 == 106 ~ 6,
    ALCDAY5 == 107 ~ 7,
    ALCDAY4 == 101 ~ 1,
    ALCDAY4 == 102 ~ 2,
    ALCDAY4 == 103 ~ 3,
    ALCDAY4 == 104 ~ 4,
    ALCDAY4 == 105 ~ 5,
    ALCDAY4 == 106 ~ 6,
    ALCDAY4 == 107 ~ 7)) |>
  mutate(sex = if_else(sex == 1, "Male", "Female")) |>
  mutate(sex = as.factor(sex),
         age = as.factor(age),
         race = as.factor(race),
         MentalIllness = as.factor(MentalIllness),
         Alcoholic = as.factor(Alcoholic),
         Incarcerated = as.factor(Incarcerated),
         SeparationDivorce = as.factor(SeparationDivorce),
         DomesticViolence = as.factor(DomesticViolence),
         PhysicalAbuse = as.factor(PhysicalAbuse),
         EmotionalAbuse = as.factor(EmotionalAbuse),
         SexualAbuse1 = as.factor(SexualAbuse1),
         SexualAbuse2 = as.factor(SexualAbuse2),
         SexualAbuse3 = as.factor(SexualAbuse3),
         Neglect1 = as.factor(Neglect1),
         Neglect2 = as.factor(Neglect2),
         SubstanceAddiction = as.factor(SubstanceAddiction)) |>
  filter(!is.na(perweek)) 

perweekplot = everything |> select(MentalIllness, sex, age, race, ALCDAY4, ALCDAY5,) |>
  mutate(perweek = case_when(
    ALCDAY5 == 101 ~ 1,
    ALCDAY5 == 102 ~ 2, 
    ALCDAY5 == 103 ~ 3,
    ALCDAY5 == 104 ~ 4, 
    ALCDAY5 == 105 ~ 5,
    ALCDAY5 == 106 ~ 6,
    ALCDAY5 == 107 ~ 7,
    ALCDAY4 == 101 ~ 1,
    ALCDAY4 == 102 ~ 2,
    ALCDAY4 == 103 ~ 3,
    ALCDAY4 == 104 ~ 4,
    ALCDAY4 == 105 ~ 5,
    ALCDAY4 == 106 ~ 6,
    ALCDAY4 == 107 ~ 7)) |>
  mutate(age = case_when(
    age == 1 ~ "18 to 24",
    age == 2 ~ "25 to 34",
    age == 3 ~ "35 to 44",
    age == 4 ~ "45 to 54",
    age == 5 ~ "55 to 64",
    age == 6 ~ "65 or > 65")) |>
  mutate(race = case_when(
    race == 1 ~ "White",
    race == 2 ~ "Black",
    race == 3 ~ "Asian",
    race == 4 ~ "AI/AN",
    race == 5 ~ "Hispanic",
    race == 6 ~ "Other"
  ))
```

## Data




## During the past 30 days, how many days per week did you have at least one drink of any alcoholic beverage such as beer, wine, a malt beverage or liquor?

- Quasipoisson regression (overdispersion = 1.234539)



```{r}
perweekall1 = glm(perweek ~ age + sex + race +
                    MentalIllness + 
                    Alcoholic + 
                    SubstanceAddiction + 
                    Incarcerated + 
                    SeparationDivorce + 
                    DomesticViolence +
                    PhysicalAbuse + 
                    EmotionalAbuse + 
                    SexualAbuse1 + 
                    SexualAbuse2 + 
                    SexualAbuse3 + 
                    Neglect1 + 
                    Neglect2, 
                  family = "quasipoisson", data = perweek)
tidy(perweekall1) |> 
  kable()
```


## Figures

```{r echo=FALSE}
one = perweekplot |>
  filter(race == "White") |>
  mutate(sex = if_else(sex == 1, "Male", "Female")) |>
  mutate(MentalIllness = if_else(MentalIllness == 1, "Yes", "No")) |>
  filter(!is.na(perweek)) |>
  filter(!is.na(MentalIllness)) |>
  group_by(perweek, MentalIllness, sex, age, race) |>
  summarise(n = n()) |>
  ggplot(aes(x = perweek, y = n, col = age, alpha = MentalIllness)) + 
  geom_line(linewidth = 1) +
  theme_minimal() +
  scale_color_viridis_d(option = "plasma", direction = 1, begin = 0.85, end = 0.35) +
  scale_alpha_manual(values = c(0.35, 1)) +
  facet_wrap(vars(race, sex)) + 
  labs(x = "Days Per Week (Alcohol Consumption)", y = "People") +
  theme(
    strip.text = element_text(color = "black", size = 16, family = "Avenir"),
    plot.title = element_text(color = "black", size = 18, family = "Avenir"),
    legend.title = element_blank(),
    legend.text = element_text(color = "black", size = 12, family = "Avenir"),
    axis.text = element_text(color = "black", size = 16, family = "Avenir"),
    axis.title = element_text(color = "black", size = 20, family = "Avenir")
  )



two = perweekplot |>
  filter(race == "Black") |>
  mutate(sex = if_else(sex == 1, "Male", "Female")) |>
  mutate(MentalIllness = if_else(MentalIllness == 1, "Yes", "No")) |>
  filter(!is.na(perweek)) |>
  filter(!is.na(MentalIllness)) |>
  group_by(perweek, MentalIllness, sex, age, race) |>
  summarise(n = n()) |>
  ggplot(aes(x = perweek, y = n, col = age, alpha = MentalIllness)) + 
  geom_line(linewidth = 1) +
  theme_minimal() +
  scale_color_viridis_d(option = "plasma", direction = 1, begin = 0.85, end = 0.35) +
  scale_alpha_manual(values = c(0.35, 1)) +
  facet_wrap(vars(race, sex)) + 
  labs(x = "Days Per Week (Alcohol Consumption)", y = "People") +
  theme(
    strip.text = element_text(color = "black", size = 16, family = "Avenir"),
    plot.title = element_text(color = "black", size = 18, family = "Avenir"),
    legend.title = element_blank(),
    legend.text = element_text(color = "black", size = 12, family = "Avenir"),
    axis.text = element_text(color = "black", size = 16, family = "Avenir"),
    axis.title = element_text(color = "black", size = 20, family = "Avenir")
  )

three = perweekplot |>
  filter(race == "Asian") |>
  mutate(sex = if_else(sex == 1, "Male", "Female")) |>
  mutate(MentalIllness = if_else(MentalIllness == 1, "Yes", "No")) |>
  filter(!is.na(perweek)) |>
  filter(!is.na(MentalIllness)) |>
  group_by(perweek, MentalIllness, sex, age, race) |>
  summarise(n = n()) |>
  ggplot(aes(x = perweek, y = n, col = age, alpha = MentalIllness)) + 
  geom_line(linewidth = 1) +
  theme_minimal() +
  scale_color_viridis_d(option = "plasma", direction = 1, begin = 0.85, end = 0.35) +
  scale_alpha_manual(values = c(0.35, 1)) +
  facet_wrap(vars(race, sex)) + 
  labs(x = "Days Per Week (Alcohol Consumption)", y = "People") +
  theme(
    strip.text = element_text(color = "black", size = 16, family = "Avenir"),
    plot.title = element_text(color = "black", size = 18, family = "Avenir"),
    legend.title = element_blank(),
    legend.text = element_text(color = "black", size = 12, family = "Avenir"),
    axis.text = element_text(color = "black", size = 16, family = "Avenir"),
    axis.title = element_text(color = "black", size = 20, family = "Avenir")
  )

five = perweekplot |>
  filter(race == "AI/AN") |>
  mutate(sex = if_else(sex == 1, "Male", "Female")) |>
  mutate(MentalIllness = if_else(MentalIllness == 1, "Yes", "No")) |>
  filter(!is.na(perweek)) |>
  filter(!is.na(MentalIllness)) |>
  group_by(perweek, MentalIllness, sex, age, race) |>
  summarise(n = n()) |>
  ggplot(aes(x = perweek, y = n, col = age, alpha = MentalIllness)) + 
  geom_line(linewidth = 1) +
  theme_minimal() +
  scale_color_viridis_d(option = "plasma", direction = 1, begin = 0.85, end = 0.35) +
  scale_alpha_manual(values = c(0.35, 1)) +
  facet_wrap(vars(race, sex)) + 
  labs(x = "Days Per Week (Alcohol Consumption)", y = "People") +
  theme(
    strip.text = element_text(color = "black", size = 16, family = "Avenir"),
    plot.title = element_text(color = "black", size = 18, family = "Avenir"),
    legend.title = element_blank(),
    legend.text = element_text(color = "black", size = 12, family = "Avenir"),
    axis.text = element_text(color = "black", size = 16, family = "Avenir"),
    axis.title = element_text(color = "black", size = 20, family = "Avenir")
  )


four = perweekplot |>
  filter(race == "Hispanic") |>
  mutate(sex = if_else(sex == 1, "Male", "Female")) |>
  mutate(MentalIllness = if_else(MentalIllness == 1, "Yes", "No")) |>
  filter(!is.na(perweek)) |>
  filter(!is.na(MentalIllness)) |>
  group_by(perweek, MentalIllness, sex, age, race) |>
  summarise(n = n()) |>
  ggplot(aes(x = perweek, y = n, col = age, alpha = MentalIllness)) + 
  geom_line(linewidth = 1) +
  theme_minimal() +
  scale_color_viridis_d(option = "plasma", direction = 1, begin = 0.85, end = 0.35) +
  scale_alpha_manual(values = c(0.35, 1)) +
  facet_wrap(vars(race, sex)) + 
  labs(x = "Days Per Week (Alcohol Consumption)", y = "People") +
  theme(
    strip.text = element_text(color = "black", size = 16, family = "Avenir"),
    plot.title = element_text(color = "black", size = 18, family = "Avenir"),
    legend.title = element_blank(),
    legend.text = element_text(color = "black", size = 12, family = "Avenir"),
    axis.text = element_text(color = "black", size = 16, family = "Avenir"),
    axis.title = element_text(color = "black", size = 20, family = "Avenir")
  )


six = perweekplot |>
  filter(race == "Other") |>
  mutate(sex = if_else(sex == 1, "Male", "Female")) |>
  mutate(MentalIllness = if_else(MentalIllness == 1, "Yes", "No")) |>
  filter(!is.na(perweek)) |>
  filter(!is.na(MentalIllness)) |>
  group_by(perweek, MentalIllness, sex, age, race) |>
  summarise(n = n()) |>
  ggplot(aes(x = perweek, y = n, col = age, alpha = MentalIllness)) + 
  geom_line(linewidth = 1) +
  theme_minimal() +
  scale_color_viridis_d(option = "plasma", direction = 1, begin = 0.85, end = 0.35) +
  scale_alpha_manual(values = c(0.35, 1)) +
  facet_wrap(vars(race, sex)) + 
  labs(x = "Days Per Week (Alcohol Consumption)", y = "People") +
  theme(
    strip.text = element_text(color = "black", size = 16, family = "Avenir"),
    plot.title = element_text(color = "black", size = 18, family = "Avenir"),
    legend.title = element_blank(),
    legend.text = element_text(color = "black", size = 12, family = "Avenir"),
    axis.text = element_text(color = "black", size = 16, family = "Avenir"),
    axis.title = element_text(color = "black", size = 20, family = "Avenir")
  )
```

```{r}
one
```


## Figures 2

```{r}
two
```

## Figure 3

```{r}
three
```

## Figure 4

```{r}
four
```

## Figure 5

```{r}
five
```


## Figure 6

```{r}
six
```

